# Generated by Django 3.0 on 2023-09-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('email_address_associate', models.EmailField(max_length=254)),
                ('email_address_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('service_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Service')),
            ],
        ),
    ]
