# Generated by Django 3.0 on 2023-09-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_leads_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='service_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Service'),
        ),
    ]
