# Generated by Django 3.0 on 2023-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230919_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='default_service_profile.png', null=True, upload_to='service_profile'),
        ),
    ]
