# Generated by Django 3.0 on 2023-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='receiver_email',
            field=models.TextField(default='ayaaninam555@gmail.com'),
            preserve_default=False,
        ),
    ]
