# Generated by Django 3.0 on 2023-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_service_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email_text_to_send_user',
            field=models.TextField(default='Its that simple! You will be contacted by a qualified professional right away!'),
        ),
    ]
