# Generated by Django 3.0 on 2023-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_service_email_text_to_send_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
